version: '3.9'

secrets:
  telegram_token:
    file: /home/telegram/preaccelerator/.token

services:
  db:
    image: "postgres:15"
    environment:
      POSTGRES_DB: preaccelerator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: "dpage/pgadmin4:6.15"
    environment:
      PGADMIN_DEFAULT_EMAIL: schilyaev.vlad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: preaccelerator_default_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  app:
    build: .
    restart: always
    depends_on:
      - db
    secrets:
      - telegram_token
    environment:
      DATABASE_NAME: preaccelerator
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SERVER: db
      DUMP_USER_ID: 105293829
      TOKEN_FILE: /run/secrets/telegram_token

volumes:
  postgres:
  pgadmin:
