version: '3.9'

secrets:
  telegram_token:
    external: true

services:
  db:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: preaccelerator
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  app:
    image: "ru.spbstu/preaccelerator-bot:1.0-snapshot"
    restart: always
    depends_on:
      - db
    secrets:
      - telegram_token
    environment:
      DATABASE_NAME: preaccelerator
      DATABASE_USER: db_user
      DATABASE_PASSWORD: db_password
      DUMP_USER_ID: 105293829
      TOKEN_FILE: /run/secrets/telegram_token

volumes:
  database-data:
