version: '3.8'

secrets:
  telegram_token:
    file: .token

services:
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_DB: preaccelerator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    network_mode: host

  pgadmin:
    image: "dpage/pgadmin4:6.13"
    environment:
      PGADMIN_DEFAULT_EMAIL: schilyaev.vlad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: preaccelerator_default_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    network_mode: host

  app:
    image: "ithersta/preaccelerator"
    depends_on:
      - postgres
    secrets:
      - telegram_token
    environment:
      DATABASE_NAME: preaccelerator
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DUMP_USER_ID: 105293829
      TOKEN_FILE: /run/secrets/telegram_token
    network_mode: host

volumes:
  postgres:
  pgadmin:
